### ISSUE TITLE
Provide HTTP endpoint for generating Events

### ISSUE THREAD

**Issue by bigg01** [bakito/batch-job-controller#3]
It would be nice to create K8S Events out of the POD while executed.

Example:
Post to controller HTTP endpoint /event/
`curl -vX POST https://server/event/ -d "{ 'event': 'Antivirus scan Started' }` 

cheers BigG01

**Comment by bakito** [comment]
Released with v1.0.0

**Comment by bigg01** [comment]
Great work! :-) and fast as lightning!
